name: Deploy Frontend to DigitalOcean Droplet
'on':
  push:
    branches:
      - master
    
    paths:
      - "my_angular_app/**"

jobs:
  build:
    name: Build angular app
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # - run: cd my_angular_app && npm install && npm install -g @angular/cli > /dev/null && npm run build --prod

    - name: Copy static files via ssh key to Server 1
      run: ${{ secrets.SSH_SCRIPT1 }}

    # - name: Copy static files via ssh key to Server 2
    #   uses: appleboy/scp-action@v0.1.4
    #   with:
    #     host: ${{ secrets.SSH_HOST2 }}
    #     username: ${{ secrets.SSH_USERNAME }}
    #     port: 22
    #     key: ${{ secrets.SSH_KEY }}
    #     source: "my_angular_app/dist/"
    #     target: var/www/html/

    # - name: Copy static files via ssh key to Server 3
    #   uses: appleboy/scp-action@v0.1.4
    #   with:
    #     host: ${{ secrets.SSH_HOST3 }}
    #     username: ${{ secrets.SSH_USERNAME }}
    #     port: 22
    #     key: ${{ secrets.SSH_KEY }}
    #     source: "my_angular_app/dist/"
    #     target: var/www/html/

    # - name: Move /dist folder contents to /html folder on Server 1
    #   uses: appleboy/ssh-action@v1.0.0
    #   with:
    #     host: ${{ secrets.SSH_HOST1 }}
    #     username: ${{ secrets.SSH_USERNAME }}
    #     port: 22
    #     key: ${{ secrets.SSH_KEY }}
    #     script: cp -R /var/www/html/my_angular_app/dist/* /var/www/html/

    # - name: Move /dist folder contents to /html folder on Server 2
    #   uses: appleboy/ssh-action@v1.0.0
    #   with:
    #     host: ${{ secrets.SSH_HOST2 }}
    #     username: ${{ secrets.SSH_USERNAME }}
    #     port: 22
    #     key: ${{ secrets.SSH_KEY }}
    #     script: cp -R /var/www/html/my_angular_app/dist/* /var/www/html/

    # - name: Move /dist folder contents to /html folder on Server 3
    #   uses: appleboy/ssh-action@v1.0.0
    #   with:
    #     host: ${{ secrets.SSH_HOST3 }}
    #     username: ${{ secrets.SSH_USERNAME }}
    #     port: 22
    #     key: ${{ secrets.SSH_KEY }}
    #     script: cp -R /var/www/html/my_angular_app/dist/* /var/www/html/
